app = "smartsafe-ppe-detection"
primary_region = "ord"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  FLY_ENVIRONMENT = "production"
  FLASK_ENV = "production"
  PYTHONPATH = "/app"
  CUDA_VISIBLE_DEVICES = ""
  YOLO_CONFIG_DIR = "/tmp/Ultralytics"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "30s"
  interval = "60s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[processes]
  app = "python smartsafe_saas_api.py"

[deploy]
  strategy = "immediate" 