CREATE TABLE IF NOT EXISTS companies (
    company_id VARCHAR(255) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    sector VARCHAR(100) NOT NULL,
    contact_person VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    address TEXT,
    max_cameras INTEGER DEFAULT 25,
    subscription_type VARCHAR(50) DEFAULT 'starter',
    billing_cycle VARCHAR(20) DEFAULT 'monthly',
    subscription_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    subscription_end TIMESTAMP,
    next_billing_date TIMESTAMP,
    auto_renewal BOOLEAN DEFAULT TRUE,
    payment_method VARCHAR(50),
    payment_status VARCHAR(20) DEFAULT 'active',
    current_balance DECIMAL(10,2) DEFAULT 0.00,
    total_paid DECIMAL(10,2) DEFAULT 0.00,
    last_payment_date TIMESTAMP,
    last_payment_amount DECIMAL(10,2),
    status VARCHAR(50) DEFAULT 'active',
    api_key VARCHAR(255) UNIQUE,
    required_ppe TEXT,
    profile_image TEXT,
    logo_url TEXT,
    sector_config JSON,
    ppe_requirements JSON,
    compliance_settings JSON,
    email_notifications BOOLEAN DEFAULT TRUE,
    sms_notifications BOOLEAN DEFAULT FALSE,
    push_notifications BOOLEAN DEFAULT TRUE,
    violation_alerts BOOLEAN DEFAULT TRUE,
    system_alerts BOOLEAN DEFAULT TRUE,
    report_notifications BOOLEAN DEFAULT TRUE,
    account_type VARCHAR(20) DEFAULT 'full',
    demo_expires_at TIMESTAMP,
    demo_limits JSON,
    telegram_notifications BOOLEAN DEFAULT FALSE,
    telegram_bot_token TEXT,
    telegram_chat_id TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sector_performance_metrics (
    id SERIAL PRIMARY KEY,
    company_id VARCHAR(255),
    sector_id VARCHAR(100),
    date DATE,
    total_detections INTEGER DEFAULT 0,
    compliance_rate DECIMAL(5,2),
    violations_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sector_ppe_configs (
    sector_id VARCHAR(100) PRIMARY KEY,
    sector_name VARCHAR(255),
    mandatory_ppe JSON,
    optional_ppe JSON,
    detection_settings JSON,
    compliance_requirements JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
