CREATE TABLE IF NOT EXISTS cameras (
    camera_id VARCHAR(255) PRIMARY KEY,
    company_id VARCHAR(255) NOT NULL,
    group_id VARCHAR(255),
    camera_name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45),
    port INTEGER DEFAULT 8080,
    rtsp_url TEXT,
    username VARCHAR(100),
    password VARCHAR(255),
    protocol VARCHAR(10) DEFAULT 'http',
    stream_path VARCHAR(255) DEFAULT '/video',
    auth_type VARCHAR(50) DEFAULT 'basic',
    resolution VARCHAR(20) DEFAULT '1920x1080',
    fps INTEGER DEFAULT 25,
    quality INTEGER DEFAULT 80,
    audio_enabled BOOLEAN DEFAULT FALSE,
    night_vision BOOLEAN DEFAULT FALSE,
    motion_detection BOOLEAN DEFAULT TRUE,
    recording_enabled BOOLEAN DEFAULT TRUE,
    camera_type VARCHAR(50) DEFAULT 'ip_camera',
    status VARCHAR(50) DEFAULT 'active',
    last_detection TIMESTAMP,
    last_test_time TIMESTAMP,
    connection_retries INTEGER DEFAULT 3,
    timeout INTEGER DEFAULT 10,
    detection_zones JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    UNIQUE(company_id, camera_name)
);

CREATE TABLE IF NOT EXISTS camera_groups (
    group_id VARCHAR(255) PRIMARY KEY,
    company_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    ppe_config JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dvr_systems (
    dvr_id VARCHAR(255) PRIMARY KEY,
    company_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    port INTEGER DEFAULT 80,
    username VARCHAR(100) DEFAULT 'admin',
    password VARCHAR(255) DEFAULT '',
    dvr_type VARCHAR(50) DEFAULT 'generic',
    protocol VARCHAR(10) DEFAULT 'http',
    api_path VARCHAR(100) DEFAULT '/api',
    rtsp_port INTEGER DEFAULT 554,
    max_channels INTEGER DEFAULT 16,
    status VARCHAR(50) DEFAULT 'inactive',
    last_test_time TIMESTAMP,
    connection_retries INTEGER DEFAULT 3,
    timeout INTEGER DEFAULT 10,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dvr_channels (
    channel_id VARCHAR(255) PRIMARY KEY,
    dvr_id VARCHAR(255) NOT NULL,
    company_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    channel_number INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'inactive',
    resolution_width INTEGER DEFAULT 1920,
    resolution_height INTEGER DEFAULT 1080,
    fps INTEGER DEFAULT 25,
    rtsp_path VARCHAR(255) DEFAULT '',
    http_path VARCHAR(255) DEFAULT '',
    detection_zones JSONB DEFAULT '[]'::jsonb,
    last_test_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dvr_id) REFERENCES dvr_systems (dvr_id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dvr_streams (
    stream_id VARCHAR(255) PRIMARY KEY,
    dvr_id VARCHAR(255) NOT NULL,
    company_id VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    stream_url TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    fps DECIMAL(5,2) DEFAULT 0,
    frame_count INTEGER DEFAULT 0,
    error_count INTEGER DEFAULT 0,
    last_frame_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dvr_id) REFERENCES dvr_systems (dvr_id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES companies (company_id) ON DELETE CASCADE,
    FOREIGN KEY (channel_id) REFERENCES dvr_channels (channel_id) ON DELETE CASCADE
);
