// Code generated by the Encore v1.56.5 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4477"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-cnv4m.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the cnv4m Encore application.
 */
export default class Client {
    public readonly camera: camera.ServiceClient
    public readonly company: company.ServiceClient
    public readonly dvr: dvr.ServiceClient
    public readonly subscription: subscription.ServiceClient
    public readonly user: user.ServiceClient
    public readonly violation: violation.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.camera = new camera.ServiceClient(base)
        this.company = new company.ServiceClient(base)
        this.dvr = new dvr.ServiceClient(base)
        this.subscription = new subscription.ServiceClient(base)
        this.user = new user.ServiceClient(base)
        this.violation = new violation.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Camera servisi - Kamera yönetimi ve CRUD operasyonları
 */
export namespace camera {
    /**
     * Kamera için veri tipleri
     */
    export interface Camera {
        "camera_id": string
        "company_id": string
        "camera_name": string
        location: string
        "ip_address": string
        port: number
        protocol: string
        "stream_path": string
        username?: string
        password?: string
        status: string
        "camera_type"?: "ip_camera" | "dvr_channel"
        "channel_number"?: number
        "dvr_id"?: string
        "group_id"?: string
        "detection_zones"?: any
        "created_at": string
    }

    export interface CameraGroup {
        "group_id": string
        "company_id": string
        name: string
        location?: string
        "group_type"?: string
        "camera_count"?: number
        "active_cameras"?: number
        "ppe_config"?: any
        "created_at": string
        "updated_at": string
    }

    export interface CreateCameraRequest {
        "camera_name": string
        "camera_location": string
        "camera_ip": string
        "camera_port"?: number
        "camera_protocol"?: string
        "camera_path"?: string
        "camera_username"?: string
        "camera_password"?: string
        "group_id"?: string
    }

    export interface CreateGroupRequest {
        name: string
        location?: string
        "group_type"?: string
        "ppe_config"?: any
    }

    export interface SuccessResponse {
        success: boolean
        error?: string
        message?: string
    }

    export interface UpdateCameraRequest {
        "camera_name"?: string
        location?: string
        "ip_address"?: string
        port?: number
        protocol?: string
        "stream_path"?: string
        status?: string
        "group_id"?: string | null
    }

    export interface UpdateGroupRequest {
        name?: string
        location?: string
        "group_type"?: string
        "ppe_config"?: any
    }

    export interface Schedule {
        id: number
        "camera_id": string
        "camera_type": string
        "day_of_week": number
        "start_time": string
        "end_time": string
        "is_enabled": boolean
        "created_at": string
    }

    export interface SaveScheduleRequest {
        "day_of_week": number
        "start_time": string
        "end_time": string
        "is_enabled": boolean
        "camera_type": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assignToGroup = this.assignToGroup.bind(this)
            this.create = this.create.bind(this)
            this.createGroup = this.createGroup.bind(this)
            this.getSnapshot = this.getSnapshot.bind(this)
            this.list = this.list.bind(this)
            this.listGroups = this.listGroups.bind(this)
            this.remove = this.remove.bind(this)
            this.removeGroup = this.removeGroup.bind(this)
            this.saveROI = this.saveROI.bind(this)
            this.update = this.update.bind(this)
            this.updateGroup = this.updateGroup.bind(this)
            this.listSchedules = this.listSchedules.bind(this)
            this.saveSchedule = this.saveSchedule.bind(this)
            this.deleteSchedule = this.deleteSchedule.bind(this)
        }

        /**
         * Kamerayı bir gruba atar
         */
        public async assignToGroup(company_id: string, camera_id: string, params: {
    "group_id": string | null
}): Promise<SuccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/assign-group`, JSON.stringify(params))
            return await resp.json() as SuccessResponse
        }

        /**
         * Yeni bir kamera ekler
         */
        public async create(company_id: string, params: CreateCameraRequest): Promise<{
    success: boolean
    "camera_id"?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/cameras`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    "camera_id"?: string
    error?: string
}
        }

        /**
         * Yeni bir kamera grubu oluşturur
         */
        public async createGroup(company_id: string, params: CreateGroupRequest): Promise<{
    success: boolean
    "group_id"?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/cameras/groups`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    "group_id"?: string
    error?: string
}
        }

        /**
         * Kameradan anlık görüntü (snapshot) alır
         */
        public async getSnapshot(company_id: string, camera_id: string): Promise<{
    success: boolean
    image?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/snapshot`)
            return await resp.json() as {
    success: boolean
    image?: string
    error?: string
}
        }

        /**
         * Şirkete ait kameraları listeler
         */
        public async list(company_id: string, params?: { status?: string }): Promise<{
    success: boolean
    cameras: Camera[]
}> {
            const path = `/company/${encodeURIComponent(company_id)}/cameras`;
            const query = params?.status ? `?status=${encodeURIComponent(params.status)}` : "";
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", path + query)
            return await resp.json() as {
    success: boolean
    cameras: Camera[]
}
        }

        /**
         * Şirkete ait kamera gruplarını listeler
         */
        public async listGroups(company_id: string): Promise<{
    success: boolean
    groups: CameraGroup[]
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/cameras/groups`)
            return await resp.json() as {
    success: boolean
    groups: CameraGroup[]
    error?: string
}
        }

        /**
         * Bir kamerayı siler
         */
        public async remove(company_id: string, camera_id: string): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}`)
            return await resp.json() as {
    success: boolean
    error?: string
}
        }

        /**
         * Kamera grubunu siler
         */
        public async removeGroup(company_id: string, group_id: string): Promise<SuccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}/cameras/groups/${encodeURIComponent(group_id)}`)
            return await resp.json() as SuccessResponse
        }

        /**
         * Kameranın ROI (Region of Interest) bölgelerini kaydeder
         */
        public async saveROI(company_id: string, camera_id: string, params: {
    zones: any[]
}): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/roi`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    error?: string
}
        }

        /**
         * Mevcut bir kamerayı günceller
         */
        public async update(company_id: string, camera_id: string, params: UpdateCameraRequest): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    error?: string
}
        }

        /**
         * Kamera grubunu günceller
         */
        public async updateGroup(company_id: string, group_id: string, params: UpdateGroupRequest): Promise<SuccessResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/company/${encodeURIComponent(company_id)}/cameras/groups/${encodeURIComponent(group_id)}`, JSON.stringify(params))
            return await resp.json() as SuccessResponse
        }

        /**
         * Kameranın zaman çizelgelerini listeler
         */
        public async listSchedules(company_id: string, camera_id: string): Promise<{
            success: boolean
            schedules: Schedule[]
            error?: string
        }> {
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/schedules`)
            return await resp.json() as {
                success: boolean
                schedules: Schedule[]
                error?: string
            }
        }

        /**
         * Zaman çizelgesi kaydeder veya günceller
         */
        public async saveSchedule(company_id: string, camera_id: string, params: SaveScheduleRequest): Promise<SuccessResponse> {
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/schedules`, JSON.stringify(params))
            return await resp.json() as SuccessResponse
        }

        /**
         * Zaman çizelgesini siler
         */
        public async deleteSchedule(company_id: string, camera_id: string, schedule_id: number): Promise<SuccessResponse> {
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}/cameras/${encodeURIComponent(camera_id)}/schedules/${encodeURIComponent(schedule_id)}`)
            return await resp.json() as SuccessResponse
        }
    }
}

export namespace company {
    export interface Company {
        "company_id": string
        "company_name": string
        email: string
        "api_key": string
        "created_at": string
        "user_count": number
    }

    export interface CompanyResponse {
        "company_id": string
        "company_name": string
        "api_key": string
        "admin_email": string
    }

    export interface CompanyStats {
        /**
         * Aktif IP kameralar + aktif DVR kanalları (toplam)
         */
        "active_cameras": number

        /**
         * Abonelik / şirket kapasitesi (dashboard paydası)
         */
        "max_cameras": number

        "today_violations": number
        "monthly_violations": number
        "avg_compliance_rate": number
        "active_workers": number
        trends: {
            cameras: number
            violations: number
            compliance: number
        }
    }

    export interface CreateCompanyParams {
        "company_name": string
        sector: string
        "contact_person": string
        email: string
        phone?: string
        address?: string
        "subscription_type"?: string
        password?: string
    }

    export interface GetCompanyResponse {
        success: boolean
        company?: any
        error?: string
    }

    export interface UpdateNotificationsRequest {
        "email_notifications": boolean
        "sms_notifications": boolean
        "push_notifications": boolean
    }

    export interface UpdateProfileRequest {
        "company_name"?: string
        sector?: string
        "contact_person"?: string
        email?: string
        phone?: string
        address?: string
        "ppe_requirements"?: any[]
        "compliance_settings"?: any
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.getById = this.getById.bind(this)
            this.getStats = this.getStats.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
            this.updateNotifications = this.updateNotifications.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.sendTestNotification = this.sendTestNotification.bind(this)
        }

        /**
         * Yeni bir şirket ve bu şirkete bağlı bir Admin kullanıcısı oluşturur.
         */
        public async create(params: CreateCompanyParams): Promise<CompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company`, JSON.stringify(params))
            return await resp.json() as CompanyResponse
        }

        /**
         * Belirli bir şirketin tüm detaylarını getirir
         */
        public async getById(company_id: string): Promise<GetCompanyResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}`)
            return await resp.json() as GetCompanyResponse
        }

        /**
         * Şirket istatistiklerini getirir (Dashboard için)
         */
        public async getStats(company_id: string): Promise<CompanyStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/stats`)
            return await resp.json() as CompanyStats
        }

        /**
         * Tüm şirketleri listeler
         */
        public async list(): Promise<{
    companies: Company[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company`)
            return await resp.json() as {
    companies: Company[]
}
        }

        /**
         * Şirket hesabını tamamen siler
         */
        public async remove(company_id: string): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}`)
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Şirket bildirim ayarlarını günceller
         */
        public async updateNotifications(company_id: string, params: UpdateNotificationsRequest): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/company/${encodeURIComponent(company_id)}/notifications`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Şirket profil bilgilerini günceller
         */
        public async updateProfile(company_id: string, params: UpdateProfileRequest): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/company/${encodeURIComponent(company_id)}`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Şirkete test bildirimi gönderir
         */
        public async sendTestNotification(company_id: string): Promise<{
    success: boolean
    message?: string
    error?: string
}> {
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/notification/test`)
            return await resp.json() as {
    success: boolean
    message?: string
    error?: string
}
        }
    }
}

/**
 * DVR servisi - DVR sistemlerinin yönetimi
 */
export namespace dvr {
    export interface CreateDVRRequest {
        name: string
        "ip_address": string
        port?: number
        username?: string
        password?: string
        "dvr_type"?: string
        protocol?: string
        "api_path"?: string
        "rtsp_port"?: number
        "max_channels"?: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.remove = this.remove.bind(this)
        }

        /**
         * Yeni bir DVR sistemi ekler
         */
        public async create(company_id: string, params: CreateDVRRequest): Promise<{
    success: boolean
    "dvr_id"?: string
    restored?: boolean
    message?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/dvr`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    "dvr_id"?: string
    restored?: boolean
    message?: string
    error?: string
}
        }

        /**
         * Şirketin DVR sistemlerini listeler
         */
        public async list(company_id: string): Promise<{
    success: boolean
    systems: any[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/dvr`)
            return await resp.json() as {
    success: boolean
    systems: any[]
}
        }

        /**
         * Bir DVR sistemini siler
         */
        public async remove(company_id: string, dvr_id: string): Promise<{
    success: boolean
    message?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}/dvr/${encodeURIComponent(dvr_id)}`)
            return await resp.json() as {
    success: boolean
    message?: string
    error?: string
}
        }

        /**
         * Bir DVR sistemini günceller
         */
        public async update(company_id: string, dvr_id: string, params: any): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/company/${encodeURIComponent(company_id)}/dvr/${encodeURIComponent(dvr_id)}`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    error?: string
}
        }
    }
}

/**
 * Subscription servisi - Plan yönetimi ve faturalandırma
 */
export namespace subscription {
    export interface SubscriptionInfo {
        "subscription_type": string
        "max_cameras": number
        status: string
        "auto_renewal": boolean
        "subscription_end"?: string
    }

    export interface ToggleAutoRenewalRequest {
        enabled: boolean
    }

    export interface UpdatePlanRequest {
        plan: string
        "max_cameras": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getInfo = this.getInfo.bind(this)
            this.toggleAutoRenewal = this.toggleAutoRenewal.bind(this)
            this.updatePlan = this.updatePlan.bind(this)
        }

        /**
         * Şirketin abonelik bilgilerini getirir
         */
        public async getInfo(company_id: string): Promise<{
    success: boolean
    subscription?: SubscriptionInfo
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/subscription`)
            return await resp.json() as {
    success: boolean
    subscription?: SubscriptionInfo
}
        }

        /**
         * Otomatik yenilemeyi açar/kapatır
         */
        public async toggleAutoRenewal(company_id: string, params: ToggleAutoRenewalRequest): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/subscription/auto-renewal`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }

        /**
         * Abonelik planını günceller
         */
        public async updatePlan(company_id: string, params: UpdatePlanRequest): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/subscription/plan`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
}
        }
    }
}

/**
 * User servisi - Şirket çalışanlarının ve operatörlerinin yönetimi
 */
export namespace user {
    export interface CreateUserRequest {
        username: string
        email: string
        password: string
        role?: string
    }

    export interface LoginRequest {
        email: string
        password: string
    }

    export interface LoginResponse {
        success: boolean
        user?: User
        error?: string
    }

    export interface User {
        "user_id": string
        "company_id": string
        username: string
        email: string
        role: string
        status: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.login = this.login.bind(this)
            this.remove = this.remove.bind(this)
        }

        /**
         * Şirkete yeni bir kullanıcı ekler
         */
        public async create(company_id: string, params: CreateUserRequest): Promise<{
    success: boolean
    "user_id"?: string
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/users`, JSON.stringify(params))
            return await resp.json() as {
    success: boolean
    "user_id"?: string
    error?: string
}
        }

        /**
         * Şirketin tüm kullanıcılarını listeler
         */
        public async list(company_id: string): Promise<{
    success: boolean
    users: User[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/users`)
            return await resp.json() as {
    success: boolean
    users: User[]
}
        }

        /**
         * Kullanıcı girişi yapar
         */
        public async login(params: LoginRequest): Promise<LoginResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as LoginResponse
        }

        /**
         * Bir kullanıcıyı siler
         */
        public async remove(company_id: string, user_id: string): Promise<{
    success: boolean
    error?: string
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/company/${encodeURIComponent(company_id)}/users/${encodeURIComponent(user_id)}`)
            return await resp.json() as {
    success: boolean
    error?: string
}
        }
    }
}

/**
 * Violation servisi - İhlallerin ve uyarıların takibi
 */
export namespace violation {
    export interface Alert {
        "alert_id": number
        "camera_id": string
        "alert_type": string
        severity: string
        title: string
        message: string
        status: string
        "created_at": string
    }

    export interface Violation {
        "violation_id": number
        "camera_id": string
        "missing_ppe": string
        "violation_type": string
        confidence: number
        timestamp: string
    }

    export interface ViolationEvent {
        "event_id": string
        "company_id": string
        /**
         * IP kamera: DB camera_id; DVR (PR3): COALESCE ile dvr_channel_id üzerinden doldurulur
         */
        "camera_id": string

        "dvr_channel_id"?: string | null
        "camera_name"?: string
        "violation_type": string
        "start_time": number
        "end_time": number
        "snapshot_path": string
        count: number
        status: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteAllEvents = this.deleteAllEvents.bind(this)
            this.getAlerts = this.getAlerts.bind(this)
            this.getEvents = this.getEvents.bind(this)
            this.getViolations = this.getViolations.bind(this)
            this.resolveAlert = this.resolveAlert.bind(this)
        }

        /**
         * Şirkete ait tüm ihlal olaylarını (violation_events) siler.
         * Diskteki snapshot dosyaları silinmez; yalnızca veritabanı kayıtları kaldırılır.
         * GET ile aynı path'te başka method kullanılamaz (Encore route çakışması).
         */
        public async deleteAllEvents(company_id: string): Promise<{
    success: boolean
    deleted: number
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/violation-events/delete-all`)
            return await resp.json() as {
    success: boolean
    deleted: number
}
        }

        /**
         * Şirketin aktif uyarılarını getirir
         */
        public async getAlerts(company_id: string): Promise<{
    success: boolean
    alerts: Alert[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/alerts`)
            return await resp.json() as {
    success: boolean
    alerts: Alert[]
}
        }

        /**
         * Şirketin ihlal olaylarını (Event-based) getirir.
         * PR3: `source_type` üzerinden ayrı join — OR / SUBSTRING yok. `camera_id` alanı API’de
         * her zaman anlamlı string (DVR’da dvr_channel_id ile geri uyum).
         */
        public async getEvents(company_id: string): Promise<{
    success: boolean
    events: ViolationEvent[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/violation-events`)
            return await resp.json() as {
    success: boolean
    events: ViolationEvent[]
}
        }

        /**
         * Şirketin ihlal raporlarını getirir (Eski sistem uyumluluk için)
         */
        public async getViolations(company_id: string): Promise<{
    success: boolean
    violations: Violation[]
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/company/${encodeURIComponent(company_id)}/violations`)
            return await resp.json() as {
    success: boolean
    violations: Violation[]
}
        }

        /**
         * Bir uyarıyı çözüldü olarak işaretler
         */
        public async resolveAlert(company_id: string, alert_id: number): Promise<{
    success: boolean
}> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/company/${encodeURIComponent(company_id)}/alerts/${encodeURIComponent(alert_id)}/resolve`)
            return await resp.json() as {
    success: boolean
}
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

export class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(globalThis);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "cnv4m-Generated-TS-Client (Encore/v1.56.5)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
