// Core API (Flask) Client
// This file is AUTO-GENERATED by core/scripts/generate_client.py
// Do not edit manually if you want to keep it in sync with the backend.

export interface CoreDiscoveryResult {
  success: boolean;
  discovery_result?: {
    cameras: Array<{
      ip: string;
      port: number;
      brand?: string;
      model?: string;
      onvif: boolean;
    }>;
  };
  error?: string;
}

export interface CoreDetectionResponse {
  success: boolean;
  message?: string;
  error?: string;
  active_camera_ids?: string[];
}

export class CoreServiceClient {
  private baseUrl: string;

  constructor(baseUrl: string = "http://localhost:5000") {
    this.baseUrl = baseUrl;
  }

  private async call(method: string, path: string, body?: any) {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method,
      headers: { "Content-Type": "application/json" },
      body: body ? JSON.stringify(body) : undefined,
    });
    return response.json();
  }
  public async index(): Promise<any> {
    return this.call("GET", `/`);
  }

  public async admin(): Promise<any> {
    return this.call("GET", `/admin`);
  }

  public async admin_post(params?: any): Promise<any> {
    return this.call("POST", `/admin`, params);
  }

  public async adminLogout(): Promise<any> {
    return this.call("GET", `/admin/logout`);
  }

  public async apiAdminCompanies(): Promise<any> {
    return this.call("GET", `/api/admin/companies`);
  }

  public async apiAdminCompanies_post(params?: any): Promise<any> {
    return this.call("POST", `/api/admin/companies`, params);
  }

  public async apiAdminCompanies_put(company_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/admin/companies/${company_id}`, params);
  }

  public async apiAdminCompanies_delete(company_id: string): Promise<any> {
    return this.call("DELETE", `/api/admin/companies/${company_id}`);
  }

  public async apiCompanyLoginRedirect(params?: any): Promise<any> {
    return this.call("POST", `/api/company-login-redirect`, params);
  }

  public async getActiveDetections(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/active-detections`);
  }

  public async apiCompanyAlerts(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/alerts`);
  }

  public async apiCompanyAlertsResolve(company_id: string, alert_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/alerts/${alert_id}/resolve`, params);
  }

  public async apiCompanyAlertsGenerate(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/alerts/generate`, params);
  }

  public async apiCompanyBillingHistory(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/billing/history`);
  }

  public async apiCompanyCameras(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras`);
  }

  public async apiCompanyCameras_post(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras`, params);
  }

  public async apiCompanyCameras_get(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}`);
  }

  public async apiCompanyCameras_delete(company_id: string, camera_id: string): Promise<any> {
    return this.call("DELETE", `/api/company/${company_id}/cameras/${camera_id}`);
  }

  public async apiCompanyCameras_put(company_id: string, camera_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/cameras/${camera_id}`, params);
  }

  public async apiCompanyCamerasDetectionHistory(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/detection/history`);
  }

  public async apiCompanyCamerasDetectionLatest(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/detection/latest`);
  }

  public async apiCompanyCamerasDetectionStream(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/detection/stream`);
  }

  public async apiCompanyCamerasGroup(company_id: string, camera_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/cameras/${camera_id}/group`, params);
  }

  public async apiCompanyCamerasMjpeg(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/mjpeg`);
  }

  public async apiCompanyCamerasProxySnapshot(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/proxy-snapshot`);
  }

  public async apiCompanyCamerasProxyStream(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/proxy-stream`);
  }

  public async apiCompanyCamerasStatus(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/status`);
  }

  public async apiCompanyCamerasStream(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/stream`);
  }

  public async getStreamDiagnostics(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/stream-status`);
  }

  public async apiCompanyCamerasTest(company_id: string, camera_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/${camera_id}/test`, params);
  }

  public async apiCompanyCamerasToggle(company_id: string, camera_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/${camera_id}/toggle`, params);
  }

  public async apiCompanyCamerasViolationsActive(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/${camera_id}/violations/active`);
  }

  public async batchProvision(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/batch-provision`, params);
  }

  public async discoverCameras(company_id: string, params?: any): Promise<any> {
    const body = (params !== undefined && (typeof params !== 'object' || params === null)) ? { mode: params } : params;
    return this.call("POST", `/api/company/${company_id}/cameras/discover`, body);
  }

  public async apiCompanyCamerasGroups(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/groups`);
  }

  public async apiCompanyCamerasGroups_post(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/groups`, params);
  }

  public async apiCompanyCamerasHealth(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/health`);
  }

  public async testCamera(company_id: string, params?: any): Promise<any> {
    const body = (params !== undefined && (typeof params !== 'object' || params === null)) ? { camera_id: params } : params;
    return this.call("POST", `/api/company/${company_id}/cameras/manual-test`, body);
  }

  public async apiCompanyCamerasModelDatabase(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/cameras/model-database`);
  }

  public async apiCompanyCamerasQuickTest(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/quick-test`, params);
  }

  public async apiCompanyCamerasSmartDiscover(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/smart-discover`, params);
  }

  public async apiCompanyCamerasSmartTest(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/smart-test`, params);
  }

  public async apiCompanyCamerasSync(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/sync`, params);
  }

  public async apiCompanyCamerasTest_post(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/cameras/test`, params);
  }

  public async apiCompanyChangePassword(company_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/change-password`, params);
  }

  public async apiCompanyChartData(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/chart-data`);
  }

  public async apiCompanyDeleteAccount(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/delete-account`, params);
  }

  public async apiCompanyDetectionResults(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/detection-results/${camera_id}`);
  }

  public async apiCompanyDetectionStatus(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/detection-status/${camera_id}`);
  }

  public async apiCompanyDetectionStats(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/detection/stats`);
  }

  public async apiCompanyDvrCameraStart(company_id: string, dvr_id: string, channel: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/camera/${channel}/start`, params);
  }

  public async apiCompanyDvrChannels(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/channels`);
  }

  public async apiCompanyDvrChannelsHealth(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/channels/health`);
  }

  public async apiCompanyDvrDelete(company_id: string, dvr_id: string): Promise<any> {
    return this.call("DELETE", `/api/company/${company_id}/dvr/${dvr_id}/delete`);
  }

  public async apiCompanyDvrDetectionResults(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/detection/results`);
  }

  public async apiCompanyDvrDetectionStart(company_id: string, dvr_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/detection/start`, params);
  }

  public async apiCompanyDvrDetectionStatus(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/detection/status`);
  }

  public async apiCompanyDvrDetectionStop(company_id: string, dvr_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/detection/stop`, params);
  }

  public async discoverDVRChannels(company_id: string, dvr_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/discover`, params);
  }

  public async apiCompanyDvrFrame(company_id: string, dvr_id: string, channel_number: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/frame/${channel_number}`);
  }

  public async apiCompanyDvrGatewayConfig(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/gateway/config`);
  }

  public async apiCompanyDvrGatewayUrls(company_id: string, dvr_id: string, channel_number: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/gateway/urls/${channel_number}`);
  }

  public async apiCompanyDvrInfo(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/info`);
  }

  public async apiCompanyDvrMjpeg(company_id: string, dvr_id: string, channel_number: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/mjpeg/${channel_number}`);
  }

  public async apiCompanyDvrPreviews(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/previews`);
  }

  public async apiCompanyDvrProxy(company_id: string, dvr_id: string, channel_number: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/proxy/${channel_number}`);
  }

  public async apiCompanyDvrReportPdf(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/report/pdf`);
  }

  public async apiCompanyDvrStatus(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/status`);
  }

  public async apiCompanyDvrStream(company_id: string, dvr_id: string, channel_number: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/stream/${channel_number}`);
  }

  public async apiCompanyDvrStream_post(company_id: string, dvr_id: string, channel_number: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/stream/${channel_number}`, params);
  }

  public async apiCompanyDvrStreamStop(company_id: string, dvr_id: string, channel_number: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/${dvr_id}/stream/${channel_number}/stop`, params);
  }

  public async apiCompanyDvrTest(company_id: string, dvr_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/${dvr_id}/test`);
  }

  public async addDVR(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/dvr/add`, params);
  }

  public async apiCompanyDvrList(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/dvr/list`);
  }

  public async apiCompanyLiveDetection(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/live-detection`);
  }

  public async apiCompanyLiveStats(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/live-stats`);
  }

  public async apiCompanyNotifications(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/notifications`);
  }

  public async apiCompanyNotifications_put(company_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/notifications`, params);
  }

  public async apiCompanyOnvifAutoProvision(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/onvif/auto-provision`, params);
  }

  public async apiCompanyOnvifChannels(company_id: string, ip: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/onvif/channels/${ip}`);
  }

  public async apiCompanyOnvifDevice(company_id: string, ip: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/onvif/device/${ip}`);
  }

  public async apiCompanyOnvifDiscover(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/onvif/discover`, params);
  }

  public async apiCompanyOnvifProfiles(company_id: string, ip: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/onvif/profiles/${ip}`);
  }

  public async apiCompanyOnvifStreamUri(company_id: string, ip: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/onvif/stream-uri/${ip}`);
  }

  public async apiCompanyOnvifTest(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/onvif/test`, params);
  }

  public async apiCompanyPaymentMethods(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/payment/methods`);
  }

  public async apiCompanyPpeConfig(company_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/ppe-config`, params);
  }

  public async apiCompanyPpeConfig_get(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/ppe-config`);
  }

  public async apiCompanyProfile(company_id: string, params?: any): Promise<any> {
    return this.call("PUT", `/api/company/${company_id}/profile`, params);
  }

  public async apiCompanyProfileUploadLogo(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/profile/upload-logo`, params);
  }

  public async apiCompanyReportsCompliance(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/reports/compliance`);
  }

  public async apiCompanyReportsExport(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/reports/export`, params);
  }

  public async apiCompanyReportsViolations(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/reports/violations`);
  }

  public async apiCompanySh17Compliance(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/sh17/compliance`, params);
  }

  public async apiCompanySh17Detect(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/sh17/detect`, params);
  }

  public async apiCompanySh17Health(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/sh17/health`);
  }

  public async apiCompanySh17Performance(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/sh17/performance`);
  }

  public async apiCompanySh17Sectors(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/sh17/sectors`);
  }

  public async apiCompanySnapshots(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/snapshots`);
  }

  public async apiCompanySnapshotsFile(company_id: string, rel_path: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/snapshots/file/${rel_path}`);
  }

  public async startDetection(company_id: string, params?: any): Promise<any> {
    const body = (params !== undefined && (typeof params !== 'object' || params === null)) ? { camera_id: params } : params;
    return this.call("POST", `/api/company/${company_id}/start-detection`, body);
  }

  public async apiCompanyStartDetectionBatch(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/start-detection-batch`, params);
  }

  public async apiCompanyStats(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/stats`);
  }

  public async stopDetection(company_id: string, params?: any): Promise<any> {
    const body = (params !== undefined && (typeof params !== 'object' || params === null)) ? { camera_id: params } : params;
    return this.call("POST", `/api/company/${company_id}/stop-detection`, body);
  }

  public async apiCompanyStopDetectionBatch(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/stop-detection-batch`, params);
  }

  public async apiCompanySubscription(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/subscription`);
  }

  public async apiCompanySubscriptionAutoRenewal(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/subscription/auto-renewal`, params);
  }

  public async apiCompanySubscriptionCancel(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/subscription/cancel`, params);
  }

  public async apiCompanySubscriptionChangePlan(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/subscription/change-plan`, params);
  }

  public async apiCompanySubscriptionPause(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/subscription/pause`, params);
  }

  public async apiCompanyUsers(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/users`);
  }

  public async apiCompanyUsers_post(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/api/company/${company_id}/users`, params);
  }

  public async apiCompanyUsers_delete(company_id: string, user_id: string): Promise<any> {
    return this.call("DELETE", `/api/company/${company_id}/users/${user_id}`);
  }

  public async apiCompanyVideoFeed(company_id: string, camera_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/video-feed/${camera_id}`);
  }

  public async apiCompanyViolationsStats(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/violations/stats`);
  }

  public async apiCompanyViolationsStream(company_id: string): Promise<any> {
    return this.call("GET", `/api/company/${company_id}/violations/stream`);
  }

  public async apiContact(params?: any): Promise<any> {
    return this.call("POST", `/api/contact`, params);
  }

  public async apiDocs(): Promise<any> {
    return this.call("GET", `/api/docs`);
  }

  public async apiDvrBrands(): Promise<any> {
    return this.call("GET", `/api/dvr/brands`);
  }

  public async apiRegister(params?: any): Promise<any> {
    return this.call("POST", `/api/register`, params);
  }

  public async apiRegisterForm(params?: any): Promise<any> {
    return this.call("POST", `/api/register-form`, params);
  }

  public async apiRequestDemo(params?: any): Promise<any> {
    return this.call("POST", `/api/request-demo`, params);
  }

  public async app(): Promise<any> {
    return this.call("GET", `/app`);
  }

  public async companyBilling(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/billing`);
  }

  public async companyCameras(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/cameras`);
  }

  public async companyDashboard(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/dashboard`);
  }

  public async companyDemoLogin(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/company/${company_id}/demo-login`, params);
  }

  public async companyLogin(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/login`);
  }

  public async companyLogin_post(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/company/${company_id}/login`, params);
  }

  public async companyLoginForm(company_id: string, params?: any): Promise<any> {
    return this.call("POST", `/company/${company_id}/login-form`, params);
  }

  public async companyProfile(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/profile`);
  }

  public async companyReports(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/reports`);
  }

  public async companySettings(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/settings`);
  }

  public async companySubscription(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/subscription`);
  }

  public async companyUpgradeModal(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/upgrade-modal`);
  }

  public async companyUsers(company_id: string): Promise<any> {
    return this.call("GET", `/company/${company_id}/users`);
  }

  public async health(): Promise<any> {
    return this.call("GET", `/health`);
  }

  public async logout(params?: any): Promise<any> {
    return this.call("POST", `/logout`, params);
  }

  public async metrics(): Promise<any> {
    return this.call("GET", `/metrics`);
  }

  public async pricing(): Promise<any> {
    return this.call("GET", `/pricing`);
  }

  public async upgradeModal(): Promise<any> {
    return this.call("GET", `/upgrade-modal`);
  }
}
