import sys
import os
import re

# Add core directory to sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
core_dir = os.path.dirname(current_dir)
sys.path.append(core_dir)

# --- ADVANCED MOCKING ---
# Mock all non-Flask modules to allow importing app.py without all dependencies
from unittest.mock import MagicMock

class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return MagicMock()

MOCK_MODULES = [
    'flask_cors', 'flask_limiter', 'flask_mail', 'sqlalchemy', 'psycopg2', 'redis', 
    'onvif_zeep', 'ultralytics', 'supervision', 'loguru', 
    'SectorPPEConfig', 'services.multitenant_system', 'database.database_adapter',
    'detection.snapshot_manager', 'detection.violation_tracker', 'integrations.dvr.dvr_ppe_integration',
    'integrations.cameras.camera_integration_manager', 'cv2', 'numpy', 'psutil', 'GPUtil', 'prometheus_client',
    'APScheduler', 'openpyxl', 'qrcode', 'bcrypt', 'jwt', 'cryptography', 'pyyaml', 'watchdog',
    'detection.utils.visual_overlay', 'integrations.cameras.ppe_detection_manager',
    'integrations.cameras.stream_watchdog', 'services.professional_config_manager', 'services.performance_optimizer',
    'models.sh17_model_manager', 'sector.sector_ppe_config', 'PIL'
]
for mod_name in MOCK_MODULES:
    sys.modules[mod_name] = Mock()

# Also mock submodules if needed
sys.modules['flask_limiter.util'] = Mock()

# Now import app
try:
    from app import app
except ImportError as e:
    print(f"Error importing app: {e}")
    # If import failed, we might need more mocks
    sys.exit(1)

FRONTEND_PATH = os.path.abspath(os.path.join(core_dir, "..", "frontend", "lib", "coreClient.ts"))

def to_camel_case(text):
    # Remove slash prefixes
    text = text.strip('/').replace('/', '_').replace('-', '_')
    # Remove params like <company_id>
    text = re.sub(r'<[^>]+>', '', text)
    # Convert under_score to camelCase
    components = [x for x in text.split('_') if x]
    if not components: return "index"
    return components[0].lower() + "".join(x.title() for x in components[1:])

def parse_path_params(path):
    # Flask format <param> or <type:param>
    params = re.findall(r'<([^>]+)>', path)
    ts_params = []
    for p in params:
        name = p.split(':')[-1]
        ts_params.append(f"{name}: string")
    return ts_params

def clean_flask_path(path):
    # Convert Flask <param> to TS ${param}
    def replacer(match):
        param = match.group(1).split(':')[-1]
        return f"${{{param}}}"
    return re.sub(r'<([^>]+)>', replacer, path)

# Collect routes
routes = []
for rule in app.url_map.iter_rules():
    # Skip static routes and core internal routes
    if rule.endpoint == 'static' or rule.rule.startswith('/static'):
        continue
    
    methods = [m for m in rule.methods if m not in ('OPTIONS', 'HEAD')]
    if not methods: continue
    
    for method in methods:
        routes.append({
            'path': rule.rule,
            'method': method,
            'endpoint': rule.endpoint
        })

# Templates
HEADER = """// Core API (Flask) Client
// This file is AUTO-GENERATED by core/scripts/generate_client.py
// Do not edit manually if you want to keep it in sync with the backend.

export interface CoreDiscoveryResult {
  success: boolean;
  discovery_result?: {
    cameras: Array<{
      ip: string;
      port: number;
      brand?: string;
      model?: string;
      onvif: boolean;
    }>;
  };
  error?: string;
}

export interface CoreDetectionResponse {
  success: boolean;
  message?: string;
  error?: string;
  active_camera_ids?: string[];
}

export class CoreServiceClient {
  private baseUrl: string;

  constructor(baseUrl: string = "http://localhost:5000") {
    this.baseUrl = baseUrl;
  }

  private async call(method: string, path: string, body?: any) {
    const response = await fetch(`${this.baseUrl}${path}`, {
      method,
      headers: { "Content-Type": "application/json" },
      body: body ? JSON.stringify(body) : undefined,
    });
    return response.json();
  }
"""

FOOTER = "}\n"

# Method generation
method_codes = []
seen_names = {}

# Sort routes to keep order stable
routes.sort(key=lambda x: x['path'])

NAME_MAPPING = {
    '/api/company/<company_id>/cameras/discover': 'discoverCameras',
    '/api/company/<company_id>/cameras/manual-test': 'testCamera',
    '/api/company/<company_id>/cameras/batch-provision': 'batchProvision',
    '/api/company/<company_id>/dvr/add': 'addDVR',
    '/api/company/<company_id>/dvr/<dvr_id>/discover': 'discoverDVRChannels',
    '/api/company/<company_id>/cameras/<camera_id>/stream-status': 'getStreamDiagnostics',
    '/api/company/<company_id>/start-detection': 'startDetection',
    '/api/company/<company_id>/stop-detection': 'stopDetection',
    '/api/company/<company_id>/active-detections': 'getActiveDetections',
}

BODY_WRAPPERS = {
    'startDetection': 'camera_id',
    'stopDetection': 'camera_id',
    'testCamera': 'camera_id',
    'discoverCameras': 'mode',
}

for route in routes:
    path = route['path']
    method = route['method']
    
    # Custom naming logic for better UX
    if path in NAME_MAPPING:
        clean_name = NAME_MAPPING[path]
    else:
        clean_name = to_camel_case(path)
        if method == 'POST' and not clean_name.startswith('post'):
            if clean_name.startswith('get'):
                clean_name = 'post' + clean_name[3:]
        
    # Handle duplicates
    full_name = f"{clean_name}_{method.lower()}" if seen_names.get(clean_name, 0) > 0 else clean_name
    seen_names[clean_name] = seen_names.get(clean_name, 0) + 1
    
    path_params = parse_path_params(path)
    clean_p = clean_flask_path(path)
    
    # Arg generation
    ts_args = list(path_params) # names with types
    
    has_body = method in ('POST', 'PUT', 'PATCH')
    if has_body:
        ts_args.append("params?: any")
    
    final_args_str = ", ".join(ts_args)

    method_code = f"  public async {full_name}({final_args_str}): Promise<any> {{\n"
    
    if has_body and clean_name in BODY_WRAPPERS:
        wrapper_key = BODY_WRAPPERS[clean_name]
        method_code += f"    const body = (params !== undefined && (typeof params !== 'object' || params === null)) ? {{ {wrapper_key}: params }} : params;\n"
        method_code += f"    return this.call(\"{method}\", `{clean_p}`, body);\n"
    else:
        method_code += f"    return this.call(\"{method}\", `{clean_p}`{', params' if has_body else ''});\n"
    
    method_code += "  }\n"
    
    method_codes.append(method_code)

# Write to file
with open(FRONTEND_PATH, "w", encoding="utf-8") as f:
    f.write(HEADER)
    f.write("\n".join(method_codes))
    f.write(FOOTER)

print(f"✅ Successfully generated {len(method_codes)} methods in {FRONTEND_PATH}")
